package com.wadpam.oauth2.dao;

/**
 * Business Methods interface for entity DConnection.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-02-19T16:14:31.437+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DConnectionDao extends GeneratedDConnectionDao {

	// TODO: declare your Business Methods here
	
}
