package com.wadpam.oauth2.dao;

/**
 * Implementation of Business Methods related to entity DConnection.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-02-19T16:14:31.437+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DConnectionDaoBean 
	extends GeneratedDConnectionDaoImpl
		implements DConnectionDao 
{

	// TODO: implement your Business Methods here

}
